config/routes.rb
Authtest::Application.routes.draw do

  devise_for :users

  root to: "home#index", locale: /en|it/

  scope "/" do
    scope "(:locale)", locale: /en|it/ do
      get "index",  to: "home#index"
      get "wip",    to: "home#wip"

      resources :articles
    end
  end

  match "*path", to: "application#routing_error", via: [:get, :post, :put, :delete, :patch]

end

app/models/article.rb
=begin

= Article

  - version:  1.00.001
  - author:   Steve A.

  Article model class.
=end
class Article < ActiveRecord::Base
  belongs_to :user                                  # [Steve, 20120212] Do not validate associated user!

  validates_presence_of :title, length: { within: 1..150 }, allow_nil: false
  validates_presence_of :content, allow_nil: false 

  scope :sort_by_user,  ->(dir) { order("users.name #{dir.to_s}, articles.created_at #{dir.to_s}") }
  #-- -------------------------------------------------------------------------
  #++

  # Retrieves the user name associated with this article
  def user_name
    self.user.nil? ? '?' : self.user.name
  end
  #-- -------------------------------------------------------------------------
  #++
end

app/controllers/articles_controller.rb
=begin

= ArticlesController

  - version:  1.00.001
  - author:   Steve A.

  Articles REST controller, DRY'ed-up with InheritedResources.
=end
class ArticlesController < InheritedResources::Base

  respond_to :html

  # Require authorization before invoking any of this controller's actions:
  before_filter :authenticate_user!                # Devise "standard" HTTP log-in strategy
  #-- -------------------------------------------------------------------------
  #++


  protected


  def permitted_params
    params.permit( article: [:title, :content, :user_id] )
  end
  #-- -------------------------------------------------------------------------
  #++
end

app/views/articles/_article_detail.html.haml
.row
  .row
    .col-xs-10
      = link_to( content_tag(:h4, article.title, class: 'text-info'), article_path(article) )
    .col-xs-1
      = link_to_if( current_user.id == article.user_id, I18n.t('edit'), edit_article_path(article), {class: "btn btn-default btn-xs"} )
    .col-xs-1
      = link_to_if( current_user.id == article.user_id, I18n.t('delete'), article_path(article), data: {confirm: I18n.t(:are_you_sure), disable_with: I18n.t(:please_wait)}, method: :delete, class: "btn btn-default btn-xs" )
  .row
    %blockquote
      %p= article.content
      %small= "#{article.user_name}, #{I18n.l(article.updated_at, format: :full)}"

app/views/articles/_article_form.html.haml
.row
- article.user ||= current_user

= simple_form_for article do |f|
  .row.col-xs-11
    = f.input_field :user_id, as: :hidden
  .row.col-xs-11
    = f.association :user, disabled: (article.user_id.to_i > 0), label: I18n.t('activerecord.models.user'), collection: User.all, prompt: I18n.t('please_select')
  .row.col-xs-11
    = f.input :title, input_html: { class: 'col-xs-8' } 
  .row.col-xs-11
    = f.input :content, input_html: { rows: 3, class: 'col-xs-12' }
  .row.col-xs-11
    %p
  .row.col-xs-11
    = f.button :submit, I18n.t('save'), {class: 'btn btn-default'}

app/views/articles/_articles_list.html.haml
.row
  - if articles.nil? || (articles && articles.length == 0)
    %p{style: "text-align: center"}
      %i= t(:no_data_found)
  - else
    %ul
      - articles.each do |a|
        = render( partial: 'article_detail', locals: {article: a} )
.row
  %p
    %hr

app/views/articles/edit.html.haml
%h3= t('articles.edit_article')
= render(partial: 'article_form', locals: {article: @article})

app/views/articles/index.html.haml
%h3= t('articles.articles')

= render(partial: 'articles_list', locals: {articles: @articles})

.row
  = link_to( t(:add_new), new_article_path() )

app/views/articles/new.html.haml
%h3= t('articles.new_title')
= render(partial: 'article_form', locals: {article: @article})

app/views/articles/show.html.haml
%h3= t('articles.show_article') + " (##{@article.id})"
= render(partial: 'article_detail', locals: {article: @article})

.row
  = link_to( t('articles.back_to_index'), articles_path() )