config/routes.rb
Authtest::Application.routes.draw do

  devise_for :users

  root to: "home#index", locale: /en|it/

  scope "/" do
    scope "(:locale)", locale: /en|it/ do
      get "index",  to: "home#index"
      get "wip",    to: "home#wip"

      resources :articles
    end
  end

  match "*path", to: "application#routing_error", via: [:get, :post, :put, :delete, :patch]

end

app/models/user.rb
=begin

= User

  - version:  1.00.001
  - author:   Steve A.

  User model class.
=end
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of   :name
  validates_uniqueness_of :name, message: :already_exists

  validates_length_of     :description,   maximum: 100
  #-- -------------------------------------------------------------------------
  #++

  # Computes a descriptive name associated with this data
  def get_full_name
    "#{name} (#{description})"
  end

  # Computes a 'full debug data dump' associated with this data
  def get_verbose_name
    "#{get_full_name}, e-mail: #{email}"
  end

  # to_s() override for debugging purposes:
  def to_s
    "[User: '#{get_full_name}']"
  end
  #-- -------------------------------------------------------------------------
  #++

end

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to( t('devise.link_log_in'), new_user_session_path(resource_name) ) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to( t('devise.link_register'), new_registration_path(resource_name) ) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to( t('devise.link_forgot_password'), new_password_path(resource_name) ) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to( t('devise.link_resend_confirm_email'), new_confirmation_path(resource_name) ) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to( t('devise.link_resend_unlock_email'), new_unlock_path(resource_name) ) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to( "#{t('devise.link_log_in_with')} #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) ) %><br />
  <% end -%>
<% end -%>